version: '3.9'

services:
  provider-crypto:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CRYPTO_KEY: <api key>
      CRYPTO_URI: https://api.coinbase.com/v2
      CRYPTO_DELAY: 10000
      CRYPTO_GRPC_PORT: 9092
      CRYPTO_PORT: 9091
    ports:
      - "9091:9091"
