version: '3.9'

services:
  provider-crypto:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CRYPTO_COINBASE_KEY: <api key>
      CRYPTO_MESSARI_KEY: <api key>
      CRYPTO_DELAY: 10000
      CRYPTO_GRPC_PORT: 9092
      CRYPTO_PORT: 9091
      CRYPTO_COINS: btc;eth;bnb;usdt;sol
    ports:
      - "9091:9091"
      - "9092:9092"
