version: '3.9'

services:
  provider-crypto:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CRYPTO_COINBASE_KEY: <key>
      CRYPTO_MESSARI_KEY: <key>
      CRYPTO_DELAY: 10001
      CRYPTO_GRPC_PORT: 9092
      CRYPTO_PORT: 9091
      CRYPTO_COINS: btc;eth;ada;usdt;sol
    ports:
      - "9091:9091"
      - "9092:9092"
