server:
  port: ${CRYPTO_PORT}

grpc:
  server:
    port: ${CRYPTO_GRPC_PORT}

app:
  coin:
    coinbase-key: ${CRYPTO_COINBASE_KEY}
    messari-key: ${CRYPTO_MESSARI_KEY}
    delay: ${CRYPTO_DELAY}
    coins: ${CRYPTO_COINS}